// lib/main.dart
// Application entry point. Initializes Firebase, registers all providers,
// and defines the named route table.

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart' hide AuthProvider;
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart';           // Generated by FlutterFire CLI
import 'providers/auth_provider.dart';
import 'providers/transaction_provider.dart';
import 'providers/budget_provider.dart';
import 'providers/theme_provider.dart';
import 'providers/connectivity_provider.dart';
import 'utils/app_theme.dart';

import 'screens/splash_screen.dart';
import 'screens/onboarding_screen.dart';
import 'screens/login_screen.dart';
import 'screens/auth_screens.dart';
import 'screens/email_verification_screen.dart';
import 'screens/main_shell.dart';
import 'screens/add_transaction_screen.dart';

void main() async {
  // Ensure Flutter bindings are ready before calling Firebase
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with platform-specific options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Connect to Firebase Emulators in debug mode
  // Comment out to test with real Firebase (e.g. email verification)
  if (kDebugMode && const bool.fromEnvironment('USE_EMULATOR', defaultValue: true)) {
    const authEmulatorPort = int.fromEnvironment('AUTH_EMULATOR_PORT', defaultValue: 9099);
    const firestoreEmulatorPort = int.fromEnvironment('FIRESTORE_EMULATOR_PORT', defaultValue: 8181);
    await FirebaseAuth.instance.useAuthEmulator('localhost', authEmulatorPort);
    FirebaseFirestore.instance.useFirestoreEmulator('localhost', firestoreEmulatorPort);
  }

  // Enable offline persistence for Firestore
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true,
    cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
  );

  // Global error handler to prevent crashes
  FlutterError.onError = (details) {
    FlutterError.presentError(details);
  };

  runApp(const BudgetTrackApp());
}

class BudgetTrackApp extends StatelessWidget {
  const BudgetTrackApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Auth provider — listens to Firebase auth state
        ChangeNotifierProvider(create: (_) => AuthProvider()),

        // Transaction provider — real-time Firestore stream
        ChangeNotifierProvider(create: (_) => TransactionProvider()),

        // Budget provider — real-time Firestore stream
        ChangeNotifierProvider(create: (_) => BudgetProvider()),

        // Theme provider — persists dark/light mode via SharedPreferences
        ChangeNotifierProvider(create: (_) => ThemeProvider()),

        // Connectivity provider — monitors network status
        ChangeNotifierProvider(create: (_) => ConnectivityProvider()),
      ],
      child: Consumer<ThemeProvider>(
        builder: (context, themeProvider, _) {
          return MaterialApp(
            title:        'BudgetTrack',
            debugShowCheckedModeBanner: false,
            theme:        AppTheme.lightTheme,
            darkTheme:    AppTheme.darkTheme,
            themeMode:    themeProvider.themeMode,
            initialRoute: '/',
            routes: {
              '/':               (_) => const SplashScreen(),
              '/onboarding':     (_) => const OnboardingScreen(),
              '/login':          (_) => const LoginScreen(),
              '/signup':         (_) => const SignupScreen(),
              '/forgot-password':(_) => const ForgotPasswordScreen(),
              '/verify-email':   (_) => const EmailVerificationScreen(),
              '/home':           (_) => const MainShell(),
              '/add-transaction':(_) => const AddTransactionScreen(),
            },
          );
        },
      ),
    );
  }
}
